apiVersion: v1
kind: Service
metadata:
  name: kafka-consumer-service
  labels:
    app: consumer
spec:
  selector:
    app: consumer
  ports:
    - name: kafka-c
      protocol: TCP
      port: 8000
      targetPort: 8000