apiVersion: v1
kind: Service
metadata:
  name: kafka-producer-service
  labels:
    app: producer
spec:
  selector:
    app: producer
  ports:
    - name: kafka-p
      protocol: TCP
      port: 8000
      targetPort: 8000